export interface WordItem {
  emoji: string;   // a single emoji that clearly depicts the word
  word: string;    // the spoken/displayed word, Title Case
}
export interface WordCategory {
  id: string;      // kebab-case unique
  title: string;   // e.g. "Yummy Food"
  emoji: string;   // category cover emoji
  items: WordItem[];  // 8 to 14 items
}
export const WORD_CATEGORIES: WordCategory[] = [
  {
    id: "yummy-food",
    title: "Yummy Food",
    emoji: "🍔",
    items: [
      { emoji: "🍞", word: "Bread" },
      { emoji: "🧀", word: "Cheese" },
      { emoji: "🥚", word: "Egg" },
      { emoji: "🍪", word: "Cookie" },
      { emoji: "🍕", word: "Pizza" },
      { emoji: "🍔", word: "Burger" },
      { emoji: "🍝", word: "Pasta" },
      { emoji: "🍦", word: "Ice Cream" },
      { emoji: "🥞", word: "Pancake" },
      { emoji: "🍫", word: "Chocolate" },
      { emoji: "🍯", word: "Honey" },
      { emoji: "🥛", word: "Milk" },
    ],
  },
  {
    id: "fruits",
    title: "Fruits",
    emoji: "🍎",
    items: [
      { emoji: "🍎", word: "Apple" },
      { emoji: "🍌", word: "Banana" },
      { emoji: "🍇", word: "Grapes" },
      { emoji: "🍊", word: "Orange" },
      { emoji: "🍓", word: "Strawberry" },
      { emoji: "🍉", word: "Watermelon" },
      { emoji: "🍑", word: "Peach" },
      { emoji: "🍍", word: "Pineapple" },
      { emoji: "🥭", word: "Mango" },
      { emoji: "🍒", word: "Cherry" },
      { emoji: "🍐", word: "Pear" },
      { emoji: "🥝", word: "Kiwi" },
    ],
  },
  {
    id: "vehicles",
    title: "Vehicles",
    emoji: "🚗",
    items: [
      { emoji: "🚗", word: "Car" },
      { emoji: "🚌", word: "Bus" },
      { emoji: "🚒", word: "Fire Truck" },
      { emoji: "🚓", word: "Police Car" },
      { emoji: "🚑", word: "Ambulance" },
      { emoji: "🚲", word: "Bicycle" },
      { emoji: "🚂", word: "Train" },
      { emoji: "✈️", word: "Airplane" },
      { emoji: "🚁", word: "Helicopter" },
      { emoji: "🚢", word: "Ship" },
      { emoji: "🚜", word: "Tractor" },
      { emoji: "🚀", word: "Rocket" },
    ],
  },
  {
    id: "around-the-home",
    title: "Around the Home",
    emoji: "🏠",
    items: [
      { emoji: "🛏️", word: "Bed" },
      { emoji: "🪑", word: "Chair" },
      { emoji: "🚪", word: "Door" },
      { emoji: "🪟", word: "Window" },
      { emoji: "💡", word: "Lamp" },
      { emoji: "🛋️", word: "Sofa" },
      { emoji: "🕰️", word: "Clock" },
      { emoji: "📺", word: "Television" },
      { emoji: "🚽", word: "Toilet" },
      { emoji: "🛁", word: "Bathtub" },
      { emoji: "🔑", word: "Key" },
    ],
  },
  {
    id: "clothes-i-wear",
    title: "Clothes I Wear",
    emoji: "👕",
    items: [
      { emoji: "👕", word: "Shirt" },
      { emoji: "👖", word: "Pants" },
      { emoji: "👗", word: "Dress" },
      { emoji: "🧦", word: "Socks" },
      { emoji: "👟", word: "Shoes" },
      { emoji: "🧢", word: "Cap" },
      { emoji: "🧥", word: "Coat" },
      { emoji: "🧤", word: "Gloves" },
      { emoji: "🧣", word: "Scarf" },
      { emoji: "👒", word: "Hat" },
    ],
  },
  {
    id: "my-body",
    title: "My Body",
    emoji: "🧒",
    items: [
      { emoji: "👁️", word: "Eye" },
      { emoji: "👂", word: "Ear" },
      { emoji: "👃", word: "Nose" },
      { emoji: "👄", word: "Mouth" },
      { emoji: "🦷", word: "Tooth" },
      { emoji: "👅", word: "Tongue" },
      { emoji: "✋", word: "Hand" },
      { emoji: "🦶", word: "Foot" },
      { emoji: "💪", word: "Arm" },
      { emoji: "🦵", word: "Leg" },
      { emoji: "🧠", word: "Brain" },
    ],
  },
  {
    id: "nature-and-weather",
    title: "Nature & Weather",
    emoji: "🌳",
    items: [
      { emoji: "☀️", word: "Sun" },
      { emoji: "🌙", word: "Moon" },
      { emoji: "⭐", word: "Star" },
      { emoji: "☁️", word: "Cloud" },
      { emoji: "🌧️", word: "Rain" },
      { emoji: "❄️", word: "Snow" },
      { emoji: "🌈", word: "Rainbow" },
      { emoji: "🌳", word: "Tree" },
      { emoji: "🌸", word: "Flower" },
      { emoji: "⚡", word: "Lightning" },
      { emoji: "🔥", word: "Fire" },
    ],
  },
  {
    id: "in-the-kitchen",
    title: "In the Kitchen",
    emoji: "🍴",
    items: [
      { emoji: "🍴", word: "Fork" },
      { emoji: "🥄", word: "Spoon" },
      { emoji: "🔪", word: "Knife" },
      { emoji: "🍽️", word: "Plate" },
      { emoji: "🥤", word: "Cup" },
      { emoji: "🍳", word: "Pan" },
      { emoji: "🫖", word: "Teapot" },
      { emoji: "🧂", word: "Salt" },
      { emoji: "🧊", word: "Ice" },
      { emoji: "🍶", word: "Bottle" },
    ],
  },
  {
    id: "toys-and-play",
    title: "Toys & Play",
    emoji: "🧸",
    items: [
      { emoji: "🧸", word: "Teddy Bear" },
      { emoji: "⚽", word: "Ball" },
      { emoji: "🪀", word: "Yo-Yo" },
      { emoji: "🎈", word: "Balloon" },
      { emoji: "🪁", word: "Kite" },
      { emoji: "🧩", word: "Puzzle" },
      { emoji: "🚂", word: "Toy Train" },
      { emoji: "🥁", word: "Drum" },
      { emoji: "🎨", word: "Paint" },
      { emoji: "🎲", word: "Dice" },
      { emoji: "🪅", word: "Piñata" },
    ],
  },
  {
    id: "jobs-people-do",
    title: "Jobs People Do",
    emoji: "👷",
    items: [
      { emoji: "👮", word: "Police Officer" },
      { emoji: "🧑‍🚒", word: "Firefighter" },
      { emoji: "🧑‍⚕️", word: "Doctor" },
      { emoji: "👩‍🏫", word: "Teacher" },
      { emoji: "👨‍🍳", word: "Chef" },
      { emoji: "👷", word: "Builder" },
      { emoji: "🧑‍🌾", word: "Farmer" },
      { emoji: "🧑‍✈️", word: "Pilot" },
      { emoji: "👩‍🚀", word: "Astronaut" },
      { emoji: "🧑‍🔧", word: "Mechanic" },
    ],
  },
];
