export interface Song {
  id: string;       // kebab-case unique
  title: string;
  emoji: string;    // a representative emoji
  lines: string[];  // each string is ONE line of lyrics, spoken/sung in order
}

export const SONGS: Song[] = [
  {
    id: "twinkle-twinkle-little-star",
    title: "Twinkle Twinkle Little Star",
    emoji: "⭐",
    lines: [
      "Twinkle, twinkle, little star,",
      "How I wonder what you are.",
      "Up above the world so high,",
      "Like a diamond in the sky.",
      "Twinkle, twinkle, little star,",
      "How I wonder what you are.",
    ],
  },
  {
    id: "the-itsy-bitsy-spider",
    title: "The Itsy Bitsy Spider",
    emoji: "🕷️",
    lines: [
      "The itsy bitsy spider",
      "Climbed up the water spout.",
      "Down came the rain",
      "And washed the spider out.",
      "Out came the sun",
      "And dried up all the rain.",
      "And the itsy bitsy spider",
      "Climbed up the spout again.",
    ],
  },
  {
    id: "old-macdonald-had-a-farm",
    title: "Old MacDonald Had a Farm",
    emoji: "🐄",
    lines: [
      "Old MacDonald had a farm,",
      "E-I-E-I-O.",
      "And on his farm he had a cow,",
      "E-I-E-I-O.",
      "With a moo moo here,",
      "And a moo moo there.",
      "Here a moo, there a moo,",
      "Everywhere a moo moo.",
      "Old MacDonald had a farm,",
      "E-I-E-I-O.",
    ],
  },
  {
    id: "row-row-row-your-boat",
    title: "Row Row Row Your Boat",
    emoji: "🚣",
    lines: [
      "Row, row, row your boat,",
      "Gently down the stream.",
      "Merrily, merrily, merrily, merrily,",
      "Life is but a dream.",
      "Row, row, row your boat,",
      "Gently down the stream.",
    ],
  },
  {
    id: "baa-baa-black-sheep",
    title: "Baa Baa Black Sheep",
    emoji: "🐑",
    lines: [
      "Baa, baa, black sheep,",
      "Have you any wool?",
      "Yes sir, yes sir,",
      "Three bags full.",
      "One for the master,",
      "And one for the dame,",
      "And one for the little boy",
      "Who lives down the lane.",
    ],
  },
  {
    id: "the-wheels-on-the-bus",
    title: "The Wheels on the Bus",
    emoji: "🚌",
    lines: [
      "The wheels on the bus go",
      "Round and round,",
      "Round and round,",
      "Round and round.",
      "The wheels on the bus go",
      "Round and round,",
      "All through the town.",
    ],
  },
  {
    id: "five-little-ducks",
    title: "Five Little Ducks",
    emoji: "🦆",
    lines: [
      "Five little ducks",
      "Went out one day,",
      "Over the hills and far away.",
      "Mother duck said,",
      "Quack, quack, quack, quack.",
      "But only four little ducks",
      "Came back.",
    ],
  },
  {
    id: "mary-had-a-little-lamb",
    title: "Mary Had a Little Lamb",
    emoji: "🐑",
    lines: [
      "Mary had a little lamb,",
      "Little lamb, little lamb.",
      "Mary had a little lamb,",
      "Its fleece was white as snow.",
      "And everywhere that Mary went,",
      "Mary went, Mary went.",
      "Everywhere that Mary went,",
      "The lamb was sure to go.",
    ],
  },
  {
    id: "if-youre-happy-and-you-know-it",
    title: "If You're Happy and You Know It",
    emoji: "😄",
    lines: [
      "If you're happy and you know it,",
      "Clap your hands.",
      "If you're happy and you know it,",
      "Clap your hands.",
      "If you're happy and you know it,",
      "Then your face will surely show it.",
      "If you're happy and you know it,",
      "Clap your hands.",
    ],
  },
  {
    id: "head-shoulders-knees-and-toes",
    title: "Head Shoulders Knees and Toes",
    emoji: "🧒",
    lines: [
      "Head, shoulders, knees and toes,",
      "Knees and toes.",
      "Head, shoulders, knees and toes,",
      "Knees and toes.",
      "And eyes and ears",
      "And mouth and nose.",
      "Head, shoulders, knees and toes,",
      "Knees and toes.",
    ],
  },
  {
    id: "hickory-dickory-dock",
    title: "Hickory Dickory Dock",
    emoji: "🕰️",
    lines: [
      "Hickory, dickory, dock,",
      "The mouse ran up the clock.",
      "The clock struck one,",
      "The mouse ran down.",
      "Hickory, dickory, dock.",
      "Tick, tock, tick, tock.",
    ],
  },
  {
    id: "the-muffin-man",
    title: "The Muffin Man",
    emoji: "🧁",
    lines: [
      "Do you know the muffin man,",
      "The muffin man, the muffin man?",
      "Do you know the muffin man",
      "Who lives on Drury Lane?",
      "Yes, I know the muffin man,",
      "The muffin man, the muffin man.",
      "Yes, I know the muffin man",
      "Who lives on Drury Lane.",
    ],
  },
  {
    id: "london-bridge-is-falling-down",
    title: "London Bridge Is Falling Down",
    emoji: "🌉",
    lines: [
      "London Bridge is falling down,",
      "Falling down, falling down.",
      "London Bridge is falling down,",
      "My fair lady.",
      "Build it up with iron bars,",
      "Iron bars, iron bars.",
      "Build it up with iron bars,",
      "My fair lady.",
    ],
  },
  {
    id: "humpty-dumpty",
    title: "Humpty Dumpty",
    emoji: "🥚",
    lines: [
      "Humpty Dumpty sat on a wall,",
      "Humpty Dumpty had a great fall.",
      "All the king's horses",
      "And all the king's men,",
      "Couldn't put Humpty",
      "Together again.",
    ],
  },
  {
    id: "jack-and-jill",
    title: "Jack and Jill",
    emoji: "🪣",
    lines: [
      "Jack and Jill went up the hill",
      "To fetch a pail of water.",
      "Jack fell down",
      "And broke his crown,",
      "And Jill came tumbling after.",
      "Up Jack got and home did trot,",
      "As fast as he could caper.",
    ],
  },
  {
    id: "rain-rain-go-away",
    title: "Rain Rain Go Away",
    emoji: "🌧️",
    lines: [
      "Rain, rain, go away,",
      "Come again another day.",
      "Little Johnny wants to play.",
      "Rain, rain, go away.",
      "Rain, rain, go away,",
      "Come again another day.",
    ],
  },
];
